### PR TITLE
Update soda to 9.0

### PR DESCRIPTION
**Pull request by xioren**

### CODE REVIEW

**Comment by mirkobrombin** [comment]
The resulting build is broken and missing the binaries. Had to remove the release for the moment

**Comment by xioren** [comment]
Hmm alright I will look into it.

**Comment by mirkobrombin** [comment]
Thanks. Ping me when you need a test.

**Comment by xioren** [comment]
I do not believe this is an issue on our end. I tried ruling out our workflow and configuration files by simply  building using the ```wine-tkg-valve-exp-bleeding.cfg``` that come with [wine-tkg-git](https://github.com/Frogging-Family/wine-tkg-git) and it fails. I have opened an issue but have yet to receive a reply. I will update once I learn more.

**Comment by mirkobrombin** [comment]
~~At least it is not a bug in our end~~ nice! I'll keep an eye on it.

**Comment by xioren** [comment]
New [PR](https://github.com/bottlesdevs/wine/pull/72).

**Pull request merged**
