### PR TITLE
Update Soda Workflow

### PR DESCRIPTION
**Pull request by xioren**
Update of #57

### CODE REVIEW

**Comment by xioren** [comment]
I switched Soda back to ```experimental_8.0``` as the upstream bug seems to be fixed.

**Comment by mirkobrombin** [comment]
The Soda build does not work for me. It is only able to launch the wine tools, while all the other apps I tested (Battle.Net, Epic Games Store, EA Launcher) does not works. There is no output at all, just a blank terminal output, could be hard to debug.

**Comment by xioren** [comment]
So Battle.net was one of the programs I tested. I just retested it again on Debian and it worked fine for me. I will test it out on Vanilla OS and see if I can reproduce. As for those warnings, I get them as well and do not believe they are related to your issue (I still want to figure out why they're there though).

**Comment by xioren** [comment]
Alright, I have done more testing and tried to pinpoint the issue but have been unable. Using both ```Caffe``` and ```Soda``` I was able to run Battle.net, EGL, and EA Launcher on Debian, Mint, and Vanilla OS. I did have some trouble on Vanilla OS but that was true for every runner I tested, not just these two (likely because I was using a live system and integrated graphics as I had to switch off ```DXVK``` to get the apps to open). As for the warnings you're seeing, I believe they are a red herring. I get them as well but they did not prevent me from installing or using any of these apps on any distro. Also, using the exact same workflow I built ```Soda``` against ```Proton 7.0``` and the warnings went away. So it is likely that there is some fundamental difference between ```7.0``` and ```8.0``` that is the cause of those warnings, or something on the ```tkg``` side.

It would be useful if we could get a third person to test out the runners as well and report their experience. As for debugging further it is difficult as I cannot reproduce the issue. I will pick it up again tomorrow but any suggestions in the mean time are appreciated.

**Comment by mirkobrombin** [comment]
I am creating a new bottle to test

**Comment by xioren** [comment]
Okay I made some progress. I figured out the ```ELFCLASS64``` warnings. ```WINE 8.0+ experimental``` needs to be built with ```_NOLIB32="wow64"``` set. Now however I am getting a ```ShellExecuteEx``` error when launching some apps, such as ```Battle.net```. So one problem fixed but now I need to figure out this new shell exception. I will update when I have more information.

**Comment by xioren** [comment]
Okay I thought I might have had a solution but it was a dead end (enabling wow64). From everything I can tell these warning are beyond the scope of this workflow and have to do with Valve's Wine itself (or tkg). There are recent issues [15988](https://forums.lutris.net/t/warnings-origin/15988) and [16186](https://forums.lutris.net/t/solved-gstreamer-errors-missing-plugins/16186) with Lutris referencing similar warnings.

Beyond that, we can do away with using the environment.sh to install dependencies and just let the tkg script handle dependency resolution which can further simplify the workflow. But that's maybe for a future pull request

**Comment by mirkobrombin** [comment]
Ya I think it is fine to ignore them for the moment. So is this ready for merge?

**Comment by xioren** [comment]
Yes, as well as [#7](https://github.com/bottlesdevs/build-tools/pull/7) and #60 .

**Comment by xioren** [comment]
Just FYI, when downloading the Soda runner properly through the app the warnings are gone. Don't ask me why.

**Pull request merged**
