### PR TITLE
Update Caffe Workflow

### PR DESCRIPTION
**Pull request by xioren**
Moved to separate branches as per your response to #57.

### CODE REVIEW

**Comment by xioren** [comment]
And reposting my response from the closed PR:

I am happy to redo the pull request with each in their own branch. As for the builds, I use the existing [environment.sh](https://github.com/bottlesdevs/build-tools/blob/main/runners/vaniglia/environment.sh) and updated [environment-tkg.sh](https://github.com/bottlesdevs/build-tools/blob/main/runners/vaniglia/environment-tkg.sh) (separate pull request). Soda and Caffe both build successfully so I am not sure if or why a GCC downgrade would still be necessary unless there was some issue with the built runners I am not aware of.

**Comment by mirkobrombin** [comment]
> And reposting my response from the closed PR:
> 
> I am happy to redo the pull request with each in their own branch. As for the builds, they use an updated [environment-tkg.sh](https://github.com/bottlesdevs/build-tools/blob/main/runners/vaniglia/environment-tkg.sh) (separate [pr](https://github.com/bottlesdevs/build-tools/pull/7)). Soda and Caffe both build successfully so I am not sure if or why a GCC downgrade would still be necessary unless there was some issue with the built runners I am not aware of.

Nice! Sorry I didn't explain it well, the problem with gcc is not building but running the resulting build in some distributions, e.g. the flatpak runtime.

**Comment by xioren** [comment]
Well I will have to build and test them locally. Is there a particular distro/app that was previously an issue without downgrading gcc?

**Comment by mirkobrombin** [comment]
I always use an Ubuntu (latest) VM for this kind of test

**Comment by xioren** [comment]
I tested both on Debian and Mint (Ubuntu) and besides the normal troubles of running Windows software they both seemed to be working. But, without knowing exactly what the original problem was I cannot say for sure it is solved. If you or anyone else wants to verify here are links for [Caffe](https://github.com/xioren/wine/releases/tag/caffe-8.18) and [Soda](https://github.com/xioren/wine/releases/tag/soda-experimental_8.0).

**Comment by mirkobrombin** [comment]
Works on Vanilla OS 2. I'll review the workflow and merge, thanks for your contribution!

**Comment by xioren** [comment]
@mirkobrombin GitHub is weird, the soda branch is being picked up by GitHub actions and run/published automatically but the caffe branch isn't. Can you instigate a manual run for Caffe so it will be available?

**Comment by xioren** [comment]
@mirkobrombin I contacted support and this was their reply:

   

> Looking at the bottlesdevs/wine repository, I notice that the build-caffe.yml workflow is currently manually disabled:
> 
> https://github.com/bottlesdevs/wine/actions/workflows/build-caffe.yml
> 
> I checked one of the push events made on the caffe branch, and our event logging looks to indicate as well that no active workflow files are on that branch.
> 
> [Enabling the workflow](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow#enabling-a-workflow) should make a difference here. Once enabled, please perform a push event on caffe and let us know if a workflow run was created as expected or not.
>

**Comment by mirkobrombin** [comment]
> @mirkobrombin I contacted support and this was their reply:
> 
> > Looking at the bottlesdevs/wine repository, I notice that the build-caffe.yml workflow is currently manually disabled:
> > https://github.com/bottlesdevs/wine/actions/workflows/build-caffe.yml
> > I checked one of the push events made on the caffe branch, and our event logging looks to indicate as well that no active workflow files are on that branch.
> > [Enabling the workflow](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow#enabling-a-workflow) should make a difference here. Once enabled, please perform a push event on caffe and let us know if a workflow run was created as expected or not.
> 
> However the issue is that it is not even showing up in the actions tab to enable. I messaged back and am awaiting a reply.

Thanks for sharing. Yes, the problem is that the workflow does not even appear in list so I can't enable nor disable it.

**Comment by xioren** [comment]
Follow up, they seem to suggest the way to solve this is through the api (github-cli?):


> I believe we're seeing this behavior due to the workflow not being present on the default branch and there being no run history for that workflow. When both of these factors are in play, the workflow is removed from the workflows list, which complicates things with it not showing in the UI that it is currently disabled.
> 
> Since the workflow exists, you should be able to enable it through the API, and once a run is triggered for that workflow, it should reappear in the Actions tab list.
> 
> https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#enable-a-workflow
> 
> Would this be possible for you to attempt?

**Comment by mirkobrombin** [comment]
Sadly it's not working, the workflow is not even listed as inactive using the `/workflows` endpoint.

**Comment by mirkobrombin** [comment]
I managed to fix it by renaming the workflow

**Pull request merged**
