### PR TITLE
Update Caffe and Soda workflows

### PR DESCRIPTION
**Pull request by xioren**
The objective is to homogenize and simplify the various runner workflows as well as bring them up to date. This brings Caffe and Soda in line with Vaniglia and hopefully makes the process of maintaining easier. It is dependent on [this](https://github.com/bottlesdevs/build-tools/pull/7) pull request.

Several open issues can be closed with this. #53, [#3067](https://github.com/bottlesdevs/Bottles/issues/3067), [#216](https://github.com/bottlesdevs/components/issues/216) 

Known Issues:
    - ```fastsync``` was switched off for Caffe as it prevented compilation (missing ```winesync``` header)
    - Soda was compiled against ```proton_8.0``` as ```experimental_8.0``` currently has an upstream [bug](https://github.com/Frogging-Family/wine-tkg-git/issues/1083).
    - I experienced permission issues when creating a new tag during workflows but I assume this is an issues with my fork.

Next Steps:
    - Utilize scripts for programmatic selection of version numbers (as Vaniglia does). They are hard coded as it stands.
 
This pull request needs scrutiny. Also I wasn't sure if this should be directed at stable or master so I have a separate (closed) [pr](https://github.com/bottlesdevs/wine/pull/56) for master if that is preferential.

Sorry at @ you @mirkobrombin but you seem like the only one maintaining this repo and thus the only one able to review.

### CODE REVIEW

**Comment by xioren** [comment]
Resetting workflows.

**Comment by mirkobrombin** [comment]
Hi, thanks for your contribution.

Initially we used different branches for different runners; stable is for Vaniglia stable, master for Vaniglia unstable, then soda for Soda stable, caffe for Caffe stable, cx for Crossover Wine stable.

For Soda and Caffe we use an old Arch Linux release to build (which was the only distro working for TKG in a while) and downgrade the repository to obtain an old gcc version since the resulting runner builds could be not compatible with recent gcc versions.

I didn't take a look at the new workflows yet. Does them solve/follow the above?

I am fine with merging everything in a single branch and handle different builds with different workflows.

**Comment by xioren** [comment]
I am happy to redo the pull request with each in their own branch. As for the builds, I use the existing [environment.sh](https://github.com/bottlesdevs/build-tools/blob/main/runners/vaniglia/environment.sh) and updated [environment-tkg.sh](https://github.com/bottlesdevs/build-tools/blob/main/runners/vaniglia/environment-tkg.sh) (separate pull request). Soda and Caffe both build successfully so I am not sure if or why a GCC downgrade would still be necessary unless there was some issue with the built runners I am not aware of.

**Comment by xioren** [comment]
I am happy to redo the pull request with each in their own branch. As for the builds, I use the existing [environment.sh](https://github.com/bottlesdevs/build-tools/blob/main/runners/vaniglia/environment.sh) and updated [environment-tkg.sh](https://github.com/bottlesdevs/build-tools/blob/main/runners/vaniglia/environment-tkg.sh) (separate pull request). Soda and Caffe both build successfully so I am not sure if or why a GCC downgrade would still be necessary unless there was some issue with the built runners I am not aware of.

**Comment by mirkobrombin** [comment]
Nice! Sorry I didn't explain it well, the problem with gcc is not building but running the resulting build in some distributions, e.g. the flatpak runtime.

**Pull request closed without merging**
